import createHttpError from 'http-errors'

import UserModel from '../models/user.model.js'
import { createSuccessResponse } from '../utils/format-response.util.js'

const getProfile = async (req, res, next) => {
  try {
    const user = await UserModel.findById(req.userId).exec()

    if (!user) {
      throw createHttpError(404, 'User kh√¥ng t·ªìn t·∫°i')
    }

    res.status(200).json(createSuccessResponse('L·∫•y th√¥ng tin ng∆∞·ªùi d√πng th√†nh c√¥ng', user))
  } catch (error) {
    next(error)
  }
}

const updateProfile = async (req, res, next) => {
  // const { avatar } = req.body
  try {
    const user = await UserModel.findOneAndUpdate({ _id: req.userId }, { ...req.body })
      // .select('+avatarId')
      .exec()

    if (user) {
      // console.log('üöÄ ~ updateProfile ~ avatar:', user.avatarId)
      // if (avatar) {
      //   myCloudinary.uploader.destroy(user.avatarId)
      // }
      return res.json(createSuccessResponse('C·∫≠p nh·∫≠t th√¥ng tin ng∆∞·ªùi d√πng th√†nh c√¥ng', user))
    }
    return next('C·∫≠p nh·∫≠t th√¥ng tin ng∆∞·ªùi d√πng th·∫•t b·∫°i')
  } catch (error) {
    next(error)
  }
}

const userMiddleware = { getProfile, updateProfile }

export default userMiddleware
